import type {
  TaskRecord,
  Permission,
  PlanStep,
  LogEntry,
} from "./types"

export const MOCK_PERMISSIONS: Permission[] = [
  {
    id: "contacts.read",
    label: "读取联系人",
    description: "允许读取通讯录中的联系人信息",
    granted: false,
  },
  {
    id: "contacts.write",
    label: "写入联系人",
    description: "允许修改通讯录中的联系人信息",
    granted: false,
  },
  {
    id: "message.send",
    label: "发送消息",
    description: "允许通过平台发送消息",
    granted: false,
  },
  {
    id: "file.save",
    label: "保存文件",
    description: "允许在本地保存文件",
    granted: false,
  },
]

export const MOCK_PLAN_STEPS: PlanStep[] = [
  {
    id: 1,
    tool: "text.generate",
    toolIcon: "FileText",
    label: "生成邀请文案",
    paramSummary: "基于活动主题生成邀请函正文",
    dependsOn: [],
    status: "success",
  },
  {
    id: 2,
    tool: "contacts.read",
    toolIcon: "Users",
    label: "读取团队联系人",
    paramSummary: '筛选标签为"核心团队"的成员',
    dependsOn: [],
    status: "success",
  },
  {
    id: 3,
    tool: "platform.send",
    toolIcon: "Send",
    label: "批量发送邀请",
    paramSummary: "通过企业微信发送给 12 位成员",
    dependsOn: [1, 2],
    status: "running",
  },
  {
    id: 4,
    tool: "file.save",
    toolIcon: "Save",
    label: "保存发送记录",
    paramSummary: "将发送日志保存为 CSV 文件",
    dependsOn: [3],
    status: "pending",
  },
]

export const MOCK_LOGS: LogEntry[] = [
  {
    id: "log-1",
    event: "agent.plan.proposed",
    summary: "方案已生成，包含 4 个执行步骤",
    status: "success",
    timestamp: "14:32:01",
  },
  {
    id: "log-2",
    event: "tool.success",
    summary: "邀请文案生成完毕（328 字）",
    status: "success",
    timestamp: "14:32:05",
  },
  {
    id: "log-3",
    event: "tool.success",
    summary: '已读取 12 位"核心团队"成员',
    status: "success",
    timestamp: "14:32:08",
  },
  {
    id: "log-4",
    event: "agent.exec.step",
    summary: "正在通过企业微信发送消息...",
    status: "running",
    timestamp: "14:32:12",
  },
]

export const MOCK_TASKS: TaskRecord[] = [
  {
    id: "task-001",
    instruction: "帮我写一封活动邀请并发送给团队",
    intent: "消息群发",
    createdAt: "2026-02-15 14:30",
    stepCount: 4,
    permissions: ["联系人读取", "消息发送", "文件保存"],
    status: "executing",
    steps: MOCK_PLAN_STEPS,
    logs: MOCK_LOGS,
    finalReply: undefined,
  },
  {
    id: "task-002",
    instruction: "生成本周项目进展报告并发送给经理",
    intent: "报告生成",
    createdAt: "2026-02-15 11:20",
    stepCount: 3,
    permissions: ["文件保存", "消息发送"],
    status: "completed",
    steps: [
      {
        id: 1,
        tool: "text.generate",
        toolIcon: "FileText",
        label: "生成周报内容",
        paramSummary: "汇总本周完成的 5 项任务",
        dependsOn: [],
        status: "success",
      },
      {
        id: 2,
        tool: "file.save",
        toolIcon: "Save",
        label: "保存为 PDF",
        paramSummary: "输出至 /reports/weekly-0215.pdf",
        dependsOn: [1],
        status: "success",
      },
      {
        id: 3,
        tool: "platform.send",
        toolIcon: "Send",
        label: "发送给经理",
        paramSummary: "通过飞书发送给张经理",
        dependsOn: [2],
        status: "success",
      },
    ],
    logs: [
      {
        id: "log-a",
        event: "agent.rendered",
        summary: "周报已生成并发送完毕",
        status: "success",
        timestamp: "11:22:30",
      },
    ],
    finalReply:
      "已为您生成本周项目进展报告（共 5 项任务），PDF 已保存并通过飞书发送给张经理。",
  },
  {
    id: "task-003",
    instruction: "整理客户反馈并生成分析摘要",
    intent: "数据分析",
    createdAt: "2026-02-14 16:45",
    stepCount: 2,
    permissions: ["文件保存"],
    status: "completed",
    steps: [
      {
        id: 1,
        tool: "text.generate",
        toolIcon: "FileText",
        label: "分析反馈数据",
        paramSummary: "分析 48 条客户反馈",
        dependsOn: [],
        status: "success",
      },
      {
        id: 2,
        tool: "file.save",
        toolIcon: "Save",
        label: "保存分析报告",
        paramSummary: "输出至 /analysis/feedback-0214.md",
        dependsOn: [1],
        status: "success",
      },
    ],
    logs: [],
    finalReply:
      "已完成客户反馈分析。正面反馈占比 72%，主要问题集中在响应速度和界面体验两个方面。详细报告已保存。",
  },
  {
    id: "task-004",
    instruction: "给新入职同事发送欢迎消息",
    intent: "消息发送",
    createdAt: "2026-02-14 09:00",
    stepCount: 2,
    permissions: ["联系人读取", "消息发送"],
    status: "failed",
    steps: [
      {
        id: 1,
        tool: "contacts.read",
        toolIcon: "Users",
        label: "查找新同事",
        paramSummary: '筛选入职日期为"本周"的成员',
        dependsOn: [],
        status: "success",
      },
      {
        id: 2,
        tool: "platform.send",
        toolIcon: "Send",
        label: "发送欢迎消息",
        paramSummary: "通过钉钉发送欢迎语",
        dependsOn: [1],
        status: "error",
        result: "钉钉接口超时，请检查网络或重试",
      },
    ],
    logs: [
      {
        id: "log-x",
        event: "tool.error",
        summary: "钉钉消息发送失败：接口超时",
        status: "error",
        timestamp: "09:01:15",
      },
    ],
    finalReply: undefined,
  },
  {
    id: "task-005",
    instruction: "帮我生成一张产品宣传海报",
    intent: "图片生成",
    createdAt: "2026-02-13 15:30",
    stepCount: 2,
    permissions: ["文件保存"],
    status: "approval",
    steps: [
      {
        id: 1,
        tool: "image.generate",
        toolIcon: "Image",
        label: "生成宣传海报",
        paramSummary: "科技风格，蓝色主题",
        dependsOn: [],
        status: "pending",
      },
      {
        id: 2,
        tool: "file.save",
        toolIcon: "Save",
        label: "保存海报文件",
        paramSummary: "输出至 /assets/poster.png",
        dependsOn: [1],
        status: "pending",
      },
    ],
    logs: [],
    finalReply: undefined,
  },
]
